baseURL = 'https://blog.suzf.net/'
languageCode = 'en-us'
title = 'Suzf Blog'
theme = "LoveIt"

[params.header]
  # desktop header mode ["fixed", "normal", "auto"]
  # 桌面端导航栏模式 ["fixed", "normal", "auto"]
  desktopMode = "fixed"
  # mobile header mode ["fixed", "normal", "auto"]
  # 移动端导航栏模式 ["fixed", "normal", "auto"]
  mobileMode = "auto"
  # Header title config
  # 页面头部导航栏标题配置
  [params.header.title]
    # URL of the LOGO
    # LOGO 的 URL
    logo = ""
    # title name
    # 标题名称
    name = "Suzf Blog"
    # you can add extra information before the name (HTML format is supported), such as icons
    # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
    post = ""
    # whether to use typeit animation for title name
    # 是否为标题显示打字机动画
    typeit = false

# Footer config
# 页面底部信息配置
[params.footer]
  enable = true
  # Custom content (HTML format is supported)
  # 自定义内容 (支持 HTML 格式)
  custom = ""
  # whether to show Hugo and theme info
  # 是否显示 Hugo 和主题信息
  hugo = false
  # whether to show copyright info
  # 是否显示版权信息
  copyright = true
  # whether to show the author
  # 是否显示作者
  author = true
  # site creation time
  # 网站创立年份
  since = 2014
  # ICP info only in China (HTML format is supported)
  # ICP 备案信息，仅在中国使用 (支持 HTML 格式)
  icp = ""
  # license info (HTML format is supported)
  # 许可协议信息 (支持 HTML 格式)
  license= '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

[params.mermaid]
  enable = true

# determines default content language ["en", "zh-cn", "fr", "pl", ...]
# 设置默认的语言 ["en", "zh-cn", "fr", "pl", ...]
defaultContentLanguage = "zh-cn"

# whether to use robots.txt
# 是否使用 robots.txt
enableRobotsTXT = true
# whether to use git commit log
# 是否使用 git 信息
enableGitInfo = false
# whether to use emoji code
# 是否使用 emoji 代码
enableEmoji = true

# ignore some build errors
# 忽略一些构建错误
ignoreErrors = ["error-remote-getjson", "error-missing-instagram-accesstoken"]

# pagination config
# 分页配置
[pagination]
  disableAliases = false
  pagerSize = 12
  path = "page"

# multilingual
# 多语言
[languages]
  [languages.zh-cn]
    weight = 1
    # language code ["en", "zh-CN", "fr", "pl", ...]
    # 网站语言, 仅在这里 CN 大写 ["en", "zh-CN", "fr", "pl", ...]
    languageCode = "zh-CN"
    # language name ["English", "简体中文", "Français", "Polski", ...]
    # 语言名称 ["English", "简体中文", "Français", "Polski", ...]
    languageName = "简体中文"
    # whether to include Chinese/Japanese/Korean
    # 是否包括中日韩文字
    hasCJKLanguage = true
    # copyright description used only for seo schema
    # 版权描述，仅仅用于 SEO
    copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
    # menu config
    # 菜单配置
    [languages.zh-cn.menu]
      [[languages.zh-cn.menu.main]]
        weight = 1
        identifier = "posts"
        name = "文章"
        url = "/posts/"
      [[languages.zh-cn.menu.main]]
        weight = 2
        identifier = "tags"
        name = "标签"
        url = "/tags/"
      [[languages.zh-cn.menu.main]]
        weight = 3
        identifier = "categories"
        name = "分类"
        url = "/categories/"
      [[languages.zh-cn.menu.main]]
        weight = 4
        identifier = "about"
        name = ""
        url = "/about/"
        # you can add extra information before the name (HTML format is supported), such as icons
        # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
        pre = "<i class='fas fa-user-circle fa-fw'></i>"
        # you can add extra information after the name (HTML format is supported), such as icons
        # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
        post = ""
        # title will be shown when you hover on this menu link
        # 当你将鼠标悬停在此菜单链接上时, 将显示标题
        title = ""
      [[languages.zh-cn.menu.main]]
        weight = 5
        identifier = "english"
        name = "English"
        url = "/en/"
    [languages.zh-cn.params]
      # site description for RSS, SEO, Open Graph and X Cards
      # 网站描述, 用于 RSS, SEO, Open Graph 和 X Cards
      description = "Suzf Blog"
      # site keywords
      # 网站关键词
      keywords = ["suzf", "suzf blog", "jeffrey"]
      # google analytics code [UA-XXXXXXXX-X]
      # 谷歌分析代号 [UA-XXXXXXXX-X]
      googleAnalytics = ""
      # author config
      # 作者配置
      [languages.zh-cn.params.author]
        name = "jeffrey"
        email = "i@suzf.net"
        link = "/about/"
      # search config
      # 搜索配置
      [languages.zh-cn.params.search]
        enable = true
        # type of search engine ["lunr", "algolia"]
        # 搜索引擎的类型 ["lunr", "algolia"]
        type = "algolia"
        # max index length of the chunked content
        # 文章内容最长索引长度
        contentLength = 4000
        # placeholder of the search bar
        # 搜索框的占位提示语
        placeholder = ""
        # max number of results length
        # 最大结果数目
        maxResultLength = 10
        # snippet length of the result
        # 结果内容片段长度
        snippetLength = 50
        # HTML tag name of the highlight part in results
        # 搜索结果中高亮部分的 HTML 标签
        highlightTag = "em"
        # whether to use the absolute URL based on the baseURL in search index
        # 是否在搜索索引中使用基于 baseURL 的绝对路径
        absoluteURL = false
        [languages.zh-cn.params.search.algolia]
          index = "index.zh-cn"
          appID = "T37N"
          searchKey = "2b7d83ac63442fef17"
      # home page config
      # 主页信息设置
      [languages.zh-cn.params.home]
        # amount of RSS pages
        # RSS 文章数目
        rss = 10
        # home page profile
        # 主页个人信息
        [languages.zh-cn.params.home.profile]
          enable = true
          # gravatar email for preferred avatar in home page
          # gravatar 邮箱，用于优先在主页显示的头像
          gravatarEmail = ""
          # URL of avatar shown in home page
          # 主页显示头像的 URL
          avatarURL = "/images/avatar.jpg"
          # title shown in home page (HTML format is supported)
          # 主页显示的网站标题 (支持 HTML 格式)
          title = "Jeffrey Su"
          # subtitle shown in home page (HTML format is supported)
          # 主页显示的网站副标题 (允许 HTML 格式)
          subtitle = ""
          # whether to use typeit animation for subtitle
          # 是否为副标题显示打字机动画
          typeit = true
          # whether to show social links
          # 是否显示社交账号
          social = true
          # disclaimer (HTML format is supported)
          # 免责声明 (支持 HTML 格式)
          disclaimer = ""
        # home page posts
        # 主页文章列表
        [languages.zh-cn.params.home.posts]
          enable = true
          # special amount of posts in each home posts page
          # 主页每页显示文章数量
          paginate = 6
      # social config in home page
      # 主页的社交信息设置
      [languages.zh-cn.params.social]
        GitHub = "suzf"
        LinkedIn = ""
        RSS = true
