name: algolia-scheduled-query

on:
  schedule:
    - cron: '45 2 * * 3' # Wednesday at 02:45 UTC
  workflow_dispatch: {}

jobs:
  run-algolia-queries:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        index: ["index.zh-cn", "index.en"]

    steps:
      - name: Query Algolia Index
        shell: bash
        env:
          APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
          API_KEY: ${{ secrets.ALGOLIA_SEARCH_KEY }}
        run: |
          # Convert APP_ID to lowercase for the URL
          LOWER_APP_ID=$(echo "${APP_ID}" | tr '[:upper:]' '[:lower:]')

          echo "INFO: Querying ${{ matrix.index }}..."

          curl --silent --show-error --fail \
            -w "Status: %{http_code}\n" \
            -o /dev/null \
            -X POST \
            -H "Content-Type: application/json" \
            -H "X-Algolia-Application-Id: ${APP_ID}" \
            -H "X-Algolia-API-Key: ${API_KEY}" \
            --data '{"params":"query=Kubernetes&hitsPerPage=10"}' \
            "https://${LOWER_APP_ID}-dsn.algolia.net/1/indexes/${{ matrix.index }}/query"
